import DOMPurify from "dompurify";

/**
 * Escapes special characters for safe interpolation into HTML strings.
 */
export function escapeHtml(str: unknown): string {
    if (str === null || str === undefined) return "";
    return String(str)
        .replace(/&/g, "&amp;")
        .replace(/</g, "&lt;")
        .replace(/>/g, "&gt;")
        .replace(/"/g, "&quot;")
        .replace(/'/g, "&#039;");
}

/**
 * Strips carriage returns and newlines to prevent header / patch injection in diff engines.
 */
export function sanitizePatchHeader(str: unknown): string {
    if (str === null || str === undefined) return "";
    return String(str)
        .replace(/[\r\n]/g, " ")
        .trim();
}

/**
 * Sanitizes HTML strings generated by diff engines, error handlers, or user inputs.
 * Strips executable scripts, event handlers, iframes, and dangerous attributes.
 */
export function sanitizeDiffHtml(dirty: string): string {
    if (!dirty) return "";
    if (typeof window === "undefined") {
        // Fallback for SSR/build environments
        return dirty;
    }

    return DOMPurify.sanitize(dirty, {
        ALLOWED_TAGS: [
            "table",
            "thead",
            "tbody",
            "tr",
            "td",
            "th",
            "div",
            "span",
            "del",
            "ins",
            "a",
            "p",
            "pre",
            "code",
            "i",
            "b",
            "u",
            "header",
            "main",
            "h1",
            "h2",
            "h3",
            "h4",
            "h5",
            "h6",
            "button",
            "section",
            "article"
        ],
        ALLOWED_ATTR: [
            "class",
            "id",
            "style",
            "title",
            "href",
            "role",
            "aria-label",
            "aria-hidden",
            "aria-selected",
            "aria-pressed",
            "aria-expanded",
            "type",
            "data-line-number"
        ],
        FORBID_TAGS: ["script", "iframe", "object", "embed", "base", "form", "input", "meta", "link"],
        FORBID_ATTR: [
            "onerror",
            "onload",
            "onclick",
            "onmouseover",
            "onfocus",
            "onblur",
            "onsubmit",
            "onkeydown",
            "onkeyup",
            "onchange"
        ],
        ALLOW_DATA_ATTR: true,
        ADD_ATTR: ["target"]
    });
}
